// We put all the hard coded files in the config file

export const IMG_CDN_URL = "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/"

export const restaurantList = [
    // {
    //     type: "restaurant",
    //     data: {
    //         type: "F",
    //         id: "304784",
    //         name: "Madhurima Veg",
    //         uuid: "cb0cb9ac-f890-4004-80c5-8b0597b68cbc",
    //         city: "15",
    //         area: "Gomti Nagar",
    //         totalRatingsString: "10000+ ratings",
    //         cloudinaryImageId: "oxqzhnlr665dy1nsvg7r",
    //         cuisines: ["Indian", "South Indian", "Chinese", "Snacks"],
    //         tags: [],
    //         costForTwo: 25000,
    //         costForTwoString: "₹250 FOR TWO",
    //         deliveryTime: 31,
    //         minDeliveryTime: 31,
    //         maxDeliveryTime: 31,
    //         slaString: "31 MINS",
    //         lastMileTravel: 6.5,
    //         slugs: {
    //             restaurant: "madhurima-veg-gomti-nagar-gomti-nagar-2",
    //             city: "lucknow",
    //         },
    //         cityState: "15",
    //         address: "A3/175, Vinay Khand, gomtinagar",
    //         locality: "Vinay Khand",
    //         parentId: 7799,
    //         unserviceable: false,
    //         veg: true,
    //         select: false,
    //         favorite: false,
    //         tradeCampaignHeaders: [],
    //         ribbon: [
    //             {
    //                 type: "PROMOTED",
    //             },
    //         ],
    //         chain: [],
    //         feeDetails: {
    //             fees: [
    //                 {
    //                     name: "distance",
    //                     fee: 5200,
    //                     message: "",
    //                 },
    //                 {
    //                     name: "time",
    //                     fee: 0,
    //                     message: "",
    //                 },
    //                 {
    //                     name: "special",
    //                     fee: 0,
    //                     message: "",
    //                 },
    //             ],
    //             totalFees: 5200,
    //             message: "",
    //             title: "Delivery Charge",
    //             amount: "5200",
    //             icon: "",
    //         },
    //         availability: {
    //             opened: true,
    //             nextOpenMessage: "",
    //             nextCloseMessage: "",
    //         },
    //         longDistanceEnabled: 0,
    //         rainMode: "NONE",
    //         thirdPartyAddress: false,
    //         thirdPartyVendor: "",
    //         adTrackingID:
    //             "cid=7026165~p=7~eid=00000188-875d-1c3f-12ff-7117003d0712",
    //         badges: {
    //             imageBased: [],
    //             textBased: [],
    //             textExtendedBadges: [],
    //         },
    //         lastMileTravelString: "6.5 kms",
    //         hasSurge: false,
    //         aggregatedDiscountInfoV3: {
    //             header: "50% OFF",
    //             subHeader: "UPTO ₹100",
    //             discountTag: "",
    //             headerTypeV2: 0,
    //         },
    //         sla: {
    //             restaurantId: "304784",
    //             deliveryTime: 31,
    //             minDeliveryTime: 31,
    //             maxDeliveryTime: 31,
    //             lastMileTravel: 6.5,
    //             lastMileDistance: 0,
    //             serviceability: "SERVICEABLE",
    //             rainMode: "NONE",
    //             longDistance: "NOT_LONG_DISTANCE",
    //             preferentialService: false,
    //             iconType: "EMPTY",
    //         },
    //         promoted: true,
    //         avgRating: "4.2",
    //         totalRatings: 10000,
    //         new: false,
    //     },
    //     subtype: "basic",
    // },
    // {
    //     type: "restaurant",
    //     data: {
    //         type: "F",
    //         id: "59321",
    //         name: "Bombay Pav Bhaji",
    //         uuid: "3404dcec-ca8c-45c1-9743-6482359b744d",
    //         city: "15",
    //         area: "Hazratganj",
    //         totalRatingsString: "1000+ ratings",
    //         cloudinaryImageId: "lr5a4tuagjxctxqkqela",
    //         cuisines: ["Street Food", "North Indian"],
    //         tags: [],
    //         costForTwo: 20000,
    //         costForTwoString: "₹200 FOR TWO",
    //         deliveryTime: 18,
    //         minDeliveryTime: 18,
    //         maxDeliveryTime: 18,
    //         slaString: "18 MINS",
    //         lastMileTravel: 0.699999988079071,
    //         slugs: {
    //             restaurant: "bombay-pav-bhaji-cinepolis-mall-gomti-nagar",
    //             city: "lucknow",
    //         },
    //         cityState: "15",
    //         address: "Near Gandhi Ashram, 9 Shanazaf Road, Hazratganj",
    //         locality: "Shahnajaf Road",
    //         parentId: 4882,
    //         unserviceable: false,
    //         veg: true,
    //         select: false,
    //         favorite: false,
    //         tradeCampaignHeaders: [],
    //         chain: [],
    //         feeDetails: {
    //             fees: [
    //                 {
    //                     name: "distance",
    //                     fee: 2300,
    //                     message: "",
    //                 },
    //                 {
    //                     name: "time",
    //                     fee: 0,
    //                     message: "",
    //                 },
    //                 {
    //                     name: "special",
    //                     fee: 0,
    //                     message: "",
    //                 },
    //             ],
    //             totalFees: 2300,
    //             message: "",
    //             title: "Delivery Charge",
    //             amount: "2300",
    //             icon: "",
    //         },
    //         availability: {
    //             opened: true,
    //             nextOpenMessage: "",
    //             nextCloseMessage: "",
    //         },
    //         longDistanceEnabled: 0,
    //         rainMode: "NONE",
    //         thirdPartyAddress: false,
    //         thirdPartyVendor: "",
    //         adTrackingID: "",
    //         badges: {
    //             imageBased: [],
    //             textBased: [],
    //             textExtendedBadges: [],
    //         },
    //         lastMileTravelString: "0.6 kms",
    //         hasSurge: false,
    //         aggregatedDiscountInfoV3: {
    //             header: "₹100 OFF",
    //             subHeader: "ABOVE ₹299",
    //             discountTag: "FLAT DEAL",
    //             headerTypeV2: 0,
    //         },
    //         sla: {
    //             restaurantId: "59321",
    //             deliveryTime: 18,
    //             minDeliveryTime: 18,
    //             maxDeliveryTime: 18,
    //             lastMileTravel: 0.699999988079071,
    //             lastMileDistance: 0,
    //             serviceability: "SERVICEABLE",
    //             rainMode: "NONE",
    //             longDistance: "NOT_LONG_DISTANCE",
    //             preferentialService: false,
    //             iconType: "EMPTY",
    //         },
    //         promoted: false,
    //         avgRating: "4.0",
    //         totalRatings: 1000,
    //         new: false,
    //     },
    //     subtype: "basic",
    // },
    // {
    //     type: "restaurant",
    //     data: {
    //         type: "F",
    //         id: "89871",
    //         name: "The Belgian Waffle Co.",
    //         uuid: "3bb8c0da-87cc-4f45-a86b-f2396719105f",
    //         city: "15",
    //         area: "Hazratganj",
    //         totalRatingsString: "5000+ ratings",
    //         cloudinaryImageId: "ll9horitrnrmfckvkfhr",
    //         cuisines: ["Waffle", "Desserts", "Ice Cream", "Beverages"],
    //         tags: [],
    //         costForTwo: 20000,
    //         costForTwoString: "₹200 FOR TWO",
    //         deliveryTime: 23,
    //         minDeliveryTime: 23,
    //         maxDeliveryTime: 23,
    //         slaString: "23 MINS",
    //         lastMileTravel: 0.10000000149011612,
    //         slugs: {
    //             restaurant: "the-belgian-waffle-hazratganj-hazratganj",
    //             city: "lucknow",
    //         },
    //         cityState: "15",
    //         address: "43/47, naval Kishore road, hazratganj , Lucknow",
    //         locality: "Naval Kishore Road",
    //         parentId: 2233,
    //         unserviceable: false,
    //         veg: true,
    //         select: false,
    //         favorite: false,
    //         tradeCampaignHeaders: [],
    //         chain: [],
    //         feeDetails: {
    //             fees: [
    //                 {
    //                     name: "distance",
    //                     fee: 2300,
    //                     message: "",
    //                 },
    //                 {
    //                     name: "time",
    //                     fee: 0,
    //                     message: "",
    //                 },
    //                 {
    //                     name: "special",
    //                     fee: 0,
    //                     message: "",
    //                 },
    //             ],
    //             totalFees: 2300,
    //             message: "",
    //             title: "Delivery Charge",
    //             amount: "2300",
    //             icon: "",
    //         },
    //         availability: {
    //             opened: true,
    //             nextOpenMessage: "",
    //             nextCloseMessage: "",
    //         },
    //         longDistanceEnabled: 0,
    //         rainMode: "NONE",
    //         thirdPartyAddress: false,
    //         thirdPartyVendor: "",
    //         adTrackingID: "",
    //         badges: {
    //             imageBased: [],
    //             textBased: [],
    //             textExtendedBadges: [],
    //         },
    //         lastMileTravelString: "0.1 kms",
    //         hasSurge: false,
    //         aggregatedDiscountInfoV3: {
    //             header: "20% OFF",
    //             subHeader: "UPTO ₹50",
    //             discountTag: "",
    //             headerTypeV2: 0,
    //         },
    //         sla: {
    //             restaurantId: "89871",
    //             deliveryTime: 23,
    //             minDeliveryTime: 23,
    //             maxDeliveryTime: 23,
    //             lastMileTravel: 0.10000000149011612,
    //             lastMileDistance: 0,
    //             serviceability: "SERVICEABLE",
    //             rainMode: "NONE",
    //             longDistance: "NOT_LONG_DISTANCE",
    //             preferentialService: false,
    //             iconType: "EMPTY",
    //         },
    //         promoted: false,
    //         avgRating: "4.4",
    //         totalRatings: 5000,
    //         new: false,
    //     },
    //     subtype: "basic",
    // },
    // {
    //     type: "restaurant",
    //     data: {
    //         type: "F",
    //         id: "63376",
    //         name: "Keventers - Milkshakes & Desserts",
    //         uuid: "ff7a8203-5ef6-49f5-b702-c366d54ce454",
    //         city: "15",
    //         area: "Hazratganj",
    //         totalRatingsString: "5000+ ratings",
    //         cloudinaryImageId: "af8216b15abde417bb0e1d8fc44fb877",
    //         cuisines: ["Beverages", "Ice Cream", "Desserts", "Healthy Food"],
    //         tags: [],
    //         costForTwo: 20000,
    //         costForTwoString: "₹200 FOR TWO",
    //         deliveryTime: 13,
    //         minDeliveryTime: 13,
    //         maxDeliveryTime: 13,
    //         slaString: "13 MINS",
    //         lastMileTravel: 0.10000000149011612,
    //         slugs: {
    //             restaurant: "keventers-sas-house-hazratganj",
    //             city: "lucknow",
    //         },
    //         cityState: "15",
    //         address: "ATM 6B, Sas House, Sapru Marg Hazratganj,Lucknow 226001",
    //         locality: "Sapru Marg",
    //         parentId: 268997,
    //         unserviceable: false,
    //         veg: true,
    //         select: false,
    //         favorite: false,
    //         tradeCampaignHeaders: [],
    //         chain: [],
    //         feeDetails: {
    //             fees: [
    //                 {
    //                     name: "distance",
    //                     fee: 2300,
    //                     message: "",
    //                 },
    //                 {
    //                     name: "time",
    //                     fee: 0,
    //                     message: "",
    //                 },
    //                 {
    //                     name: "special",
    //                     fee: 0,
    //                     message: "",
    //                 },
    //             ],
    //             totalFees: 2300,
    //             message: "",
    //             title: "Delivery Charge",
    //             amount: "2300",
    //             icon: "",
    //         },
    //         availability: {
    //             opened: true,
    //             nextOpenMessage: "",
    //             nextCloseMessage: "",
    //         },
    //         longDistanceEnabled: 0,
    //         rainMode: "NONE",
    //         thirdPartyAddress: false,
    //         thirdPartyVendor: "",
    //         adTrackingID: "",
    //         badges: {
    //             imageBased: [],
    //             textBased: [],
    //             textExtendedBadges: [],
    //         },
    //         lastMileTravelString: "0.1 kms",
    //         hasSurge: false,
    //         aggregatedDiscountInfoV3: {
    //             header: "40% OFF",
    //             subHeader: "UPTO ₹80",
    //             discountTag: "",
    //             headerTypeV2: 0,
    //         },
    //         sla: {
    //             restaurantId: "63376",
    //             deliveryTime: 13,
    //             minDeliveryTime: 13,
    //             maxDeliveryTime: 13,
    //             lastMileTravel: 0.10000000149011612,
    //             lastMileDistance: 0,
    //             serviceability: "SERVICEABLE",
    //             rainMode: "NONE",
    //             longDistance: "NOT_LONG_DISTANCE",
    //             preferentialService: false,
    //             iconType: "EMPTY",
    //         },
    //         promoted: false,
    //         avgRating: "4.2",
    //         totalRatings: 5000,
    //         new: false,
    //     },
    //     subtype: "basic",
    // },
    // {
    //     type: "restaurant",
    //     data: {
    //         type: "F",
    //         id: "437799",
    //         name: "Kwality Walls Frozen Dessert and Ice Cream Shop",
    //         uuid: "40b0aa28-fb57-443c-9f00-b3d696f55012",
    //         city: "15",
    //         area: "Aliganj",
    //         totalRatingsString: "1000+ ratings",
    //         cloudinaryImageId: "jyhobfiuhab8hyhmnsyw",
    //         cuisines: ["Desserts", "Ice Cream", "Ice Cream Cakes"],
    //         tags: [],
    //         costForTwo: 30000,
    //         costForTwoString: "₹300 FOR TWO",
    //         deliveryTime: 27,
    //         minDeliveryTime: 27,
    //         maxDeliveryTime: 27,
    //         slaString: "27 MINS",
    //         lastMileTravel: 7.800000190734863,
    //         slugs: {
    //             restaurant:
    //                 "kwality-walls-frozen-dessert-and-ice-cream-shop-aliganj-aliganj-4",
    //             city: "lucknow",
    //         },
    //         cityState: "15",
    //         address:
    //             "AMAN STORE : 1/747 VIKAS NAGAR LUCKNOW, NAGAR NIGAM FOOD SAFETY , ZONE - 9, LUCKNOW , UTTAR PRADESH , 226022",
    //         locality: "Vikas Nagar",
    //         parentId: 582,
    //         unserviceable: false,
    //         veg: true,
    //         select: false,
    //         favorite: false,
    //         tradeCampaignHeaders: [],
    //         ribbon: [
    //             {
    //                 type: "PROMOTED",
    //             },
    //         ],
    //         chain: [],
    //         feeDetails: {
    //             fees: [
    //                 {
    //                     name: "distance",
    //                     fee: 5100,
    //                     message: "",
    //                 },
    //                 {
    //                     name: "time",
    //                     fee: 0,
    //                     message: "",
    //                 },
    //                 {
    //                     name: "special",
    //                     fee: 0,
    //                     message: "",
    //                 },
    //             ],
    //             totalFees: 5100,
    //             message: "",
    //             title: "Delivery Charge",
    //             amount: "5100",
    //             icon: "",
    //         },
    //         availability: {
    //             opened: true,
    //             nextOpenMessage: "",
    //             nextCloseMessage: "",
    //         },
    //         longDistanceEnabled: 0,
    //         rainMode: "NONE",
    //         thirdPartyAddress: false,
    //         thirdPartyVendor: "",
    //         adTrackingID:
    //             "cid=7043567~p=25~eid=00000188-875d-1c3f-12ff-711d003d196c",
    //         badges: {
    //             imageBased: [],
    //             textBased: [],
    //             textExtendedBadges: [],
    //         },
    //         lastMileTravelString: "7.8 kms",
    //         hasSurge: false,
    //         aggregatedDiscountInfoV3: {
    //             header: "50% OFF",
    //             subHeader: "UPTO ₹100",
    //             discountTag: "",
    //             headerTypeV2: 0,
    //         },
    //         sla: {
    //             restaurantId: "437799",
    //             deliveryTime: 27,
    //             minDeliveryTime: 27,
    //             maxDeliveryTime: 27,
    //             lastMileTravel: 7.800000190734863,
    //             lastMileDistance: 0,
    //             serviceability: "SERVICEABLE",
    //             rainMode: "NONE",
    //             longDistance: "NOT_LONG_DISTANCE",
    //             preferentialService: false,
    //             iconType: "EMPTY",
    //         },
    //         promoted: true,
    //         avgRating: "4.5",
    //         totalRatings: 1000,
    //         new: false,
    //     },
    //     subtype: "basic",
    // },
    // {
    //     type: "restaurant",
    //     data: {
    //         type: "F",
    //         id: "220459",
    //         name: "NIC Ice Creams",
    //         uuid: "e98f8495-b2ea-408e-8c88-e616c33e26fa",
    //         city: "15",
    //         area: "Hazratganj",
    //         totalRatingsString: "5000+ ratings",
    //         cloudinaryImageId: "d461cb7eac503656a2b4bb13e7c60b97",
    //         cuisines: ["Desserts", "Ice Cream"],
    //         tags: [],
    //         costForTwo: 12000,
    //         costForTwoString: "₹120 FOR TWO",
    //         deliveryTime: 14,
    //         minDeliveryTime: 14,
    //         maxDeliveryTime: 14,
    //         slaString: "14 MINS",
    //         lastMileTravel: 0.8999999761581421,
    //         slugs: {
    //             restaurant: "nic-natural-ice-creams-hazratganj-hazratganj",
    //             city: "lucknow",
    //         },
    //         cityState: "15",
    //         address:
    //             "43/124, B M Plaza, UGF Part 3 & 4Naval Kishor Road,Hazratganj,Lucknow, UP 226001",
    //         locality: "Naval Kishor Road",
    //         parentId: 6249,
    //         unserviceable: false,
    //         veg: true,
    //         select: false,
    //         favorite: false,
    //         tradeCampaignHeaders: [],
    //         chain: [],
    //         feeDetails: {
    //             fees: [
    //                 {
    //                     name: "distance",
    //                     fee: 2300,
    //                     message: "",
    //                 },
    //                 {
    //                     name: "time",
    //                     fee: 0,
    //                     message: "",
    //                 },
    //                 {
    //                     name: "special",
    //                     fee: 0,
    //                     message: "",
    //                 },
    //             ],
    //             totalFees: 2300,
    //             message: "",
    //             title: "Delivery Charge",
    //             amount: "2300",
    //             icon: "",
    //         },
    //         availability: {
    //             opened: true,
    //             nextOpenMessage: "",
    //             nextCloseMessage: "",
    //         },
    //         longDistanceEnabled: 0,
    //         rainMode: "NONE",
    //         thirdPartyAddress: false,
    //         thirdPartyVendor: "",
    //         adTrackingID: "",
    //         badges: {
    //             imageBased: [],
    //             textBased: [],
    //             textExtendedBadges: [],
    //         },
    //         lastMileTravelString: "0.8 kms",
    //         hasSurge: false,
    //         aggregatedDiscountInfoV3: {
    //             header: "50% OFF",
    //             subHeader: "UPTO ₹100",
    //             discountTag: "",
    //             headerTypeV2: 0,
    //         },
    //         sla: {
    //             restaurantId: "220459",
    //             deliveryTime: 14,
    //             minDeliveryTime: 14,
    //             maxDeliveryTime: 14,
    //             lastMileTravel: 0.8999999761581421,
    //             lastMileDistance: 0,
    //             serviceability: "SERVICEABLE",
    //             rainMode: "NONE",
    //             longDistance: "NOT_LONG_DISTANCE",
    //             preferentialService: false,
    //             iconType: "EMPTY",
    //         },
    //         promoted: false,
    //         avgRating: "4.6",
    //         totalRatings: 5000,
    //         new: false,
    //     },
    //     subtype: "basic",
    // },
    // {
    //     type: "restaurant",
    //     data: {
    //         type: "F",
    //         id: "59853",
    //         name: "Moti Mahal",
    //         uuid: "72b51ff0-9494-4023-bf6c-6f41ddef10e1",
    //         city: "15",
    //         area: "Hazratganj",
    //         totalRatingsString: "10000+ ratings",
    //         cloudinaryImageId: "htnnr5pwpcvu3jpaavng",
    //         cuisines: ["Indian", "Chinese", "Continental"],
    //         tags: [],
    //         costForTwo: 60000,
    //         costForTwoString: "₹600 FOR TWO",
    //         deliveryTime: 21,
    //         minDeliveryTime: 21,
    //         maxDeliveryTime: 21,
    //         slaString: "21 MINS",
    //         lastMileTravel: 1.399999976158142,
    //         slugs: {
    //             restaurant: "moti-mahal-hazratganj-hazratganj",
    //             city: "lucknow",
    //         },
    //         cityState: "15",
    //         address:
    //             "75, Mahatma Gandhi Marg, Next to Central Bank of India, Hazratganj, Lucknow",
    //         locality: "Mahatma Gandhi Marg",
    //         parentId: 21767,
    //         unserviceable: false,
    //         veg: true,
    //         select: false,
    //         favorite: false,
    //         tradeCampaignHeaders: [],
    //         chain: [],
    //         feeDetails: {
    //             fees: [
    //                 {
    //                     name: "distance",
    //                     fee: 2300,
    //                     message: "",
    //                 },
    //                 {
    //                     name: "time",
    //                     fee: 0,
    //                     message: "",
    //                 },
    //                 {
    //                     name: "special",
    //                     fee: 0,
    //                     message: "",
    //                 },
    //             ],
    //             totalFees: 2300,
    //             message: "",
    //             title: "Delivery Charge",
    //             amount: "2300",
    //             icon: "",
    //         },
    //         availability: {
    //             opened: true,
    //             nextOpenMessage: "",
    //             nextCloseMessage: "",
    //         },
    //         longDistanceEnabled: 0,
    //         rainMode: "NONE",
    //         thirdPartyAddress: false,
    //         thirdPartyVendor: "",
    //         adTrackingID: "",
    //         badges: {
    //             imageBased: [],
    //             textBased: [],
    //             textExtendedBadges: [],
    //         },
    //         lastMileTravelString: "1.3 kms",
    //         hasSurge: false,
    //         sla: {
    //             restaurantId: "59853",
    //             deliveryTime: 21,
    //             minDeliveryTime: 21,
    //             maxDeliveryTime: 21,
    //             lastMileTravel: 1.399999976158142,
    //             lastMileDistance: 0,
    //             serviceability: "SERVICEABLE",
    //             rainMode: "NONE",
    //             longDistance: "NOT_LONG_DISTANCE",
    //             preferentialService: false,
    //             iconType: "EMPTY",
    //         },
    //         promoted: false,
    //         avgRating: "4.0",
    //         totalRatings: 10000,
    //         new: false,
    //     },
    //     subtype: "basic",
    // },
    // {
    //     type: "restaurant",
    //     data: {
    //         type: "F",
    //         id: "695062",
    //         name: "The Punjabi Junction",
    //         uuid: "22382005-9581-42f8-9e53-89d7bc31da1e",
    //         city: "15",
    //         area: "Hazratganj",
    //         totalRatingsString: "Too Few Ratings",
    //         cloudinaryImageId: "9cf5ca6956d161e963aa1ffc639dcb45",
    //         cuisines: ["North Indian"],
    //         tags: [],
    //         costForTwo: 11000,
    //         costForTwoString: "₹110 FOR TWO",
    //         deliveryTime: 21,
    //         minDeliveryTime: 21,
    //         maxDeliveryTime: 21,
    //         slaString: "21 MINS",
    //         lastMileTravel: 0.20000000298023224,
    //         slugs: {
    //             restaurant: "the-punjabi-junction-hazratganj-hazratganj",
    //             city: "lucknow",
    //         },
    //         cityState: "15",
    //         address:
    //             "NK-232, Prem Nagar, Hazratganj, Lucknow, Uttar Pradesh 226001, India",
    //         locality: "Prem Nagar",
    //         parentId: 13471,
    //         unserviceable: false,
    //         veg: true,
    //         select: false,
    //         favorite: false,
    //         tradeCampaignHeaders: [],
    //         chain: [],
    //         feeDetails: {
    //             fees: [
    //                 {
    //                     name: "distance",
    //                     fee: 2300,
    //                     message: "",
    //                 },
    //                 {
    //                     name: "time",
    //                     fee: 0,
    //                     message: "",
    //                 },
    //                 {
    //                     name: "special",
    //                     fee: 0,
    //                     message: "",
    //                 },
    //             ],
    //             totalFees: 2300,
    //             message: "",
    //             title: "Delivery Charge",
    //             amount: "2300",
    //             icon: "",
    //         },
    //         availability: {
    //             opened: true,
    //             nextOpenMessage: "",
    //             nextCloseMessage: "",
    //         },
    //         longDistanceEnabled: 0,
    //         rainMode: "NONE",
    //         thirdPartyAddress: false,
    //         thirdPartyVendor: "",
    //         adTrackingID: "",
    //         badges: {
    //             imageBased: [],
    //             textBased: [],
    //             textExtendedBadges: [],
    //         },
    //         lastMileTravelString: "0.2 kms",
    //         hasSurge: false,
    //         sla: {
    //             restaurantId: "695062",
    //             deliveryTime: 21,
    //             minDeliveryTime: 21,
    //             maxDeliveryTime: 21,
    //             lastMileTravel: 0.20000000298023224,
    //             lastMileDistance: 0,
    //             serviceability: "SERVICEABLE",
    //             rainMode: "NONE",
    //             longDistance: "NOT_LONG_DISTANCE",
    //             preferentialService: false,
    //             iconType: "EMPTY",
    //         },
    //         promoted: false,
    //         avgRating: "--",
    //         totalRatings: 0,
    //         new: false,
    //     },
    //     subtype: "basic",
    // },
    // {
    //     type: "restaurant",
    //     data: {
    //         type: "F",
    //         id: "63849",
    //         name: "Durgma Restaurant",
    //         uuid: "e40c3bd4-1fa2-40ec-bb22-db09152c7363",
    //         city: "15",
    //         area: "Lalbagh",
    //         totalRatingsString: "5000+ ratings",
    //         cloudinaryImageId: "lekhu2tvgosiilgq97ar",
    //         cuisines: ["North Indian", "Thalis", "Desserts"],
    //         tags: [],
    //         costForTwo: 25000,
    //         costForTwoString: "₹250 FOR TWO",
    //         deliveryTime: 18,
    //         minDeliveryTime: 18,
    //         maxDeliveryTime: 18,
    //         slaString: "18 MINS",
    //         lastMileTravel: 1.399999976158142,
    //         slugs: {
    //             restaurant: "durgma-restaurant-hazratganj-hazratganj",
    //             city: "lucknow",
    //         },
    //         cityState: "15",
    //         address: "Basement, Durgma Towers, Lalbagh, Lucknow",
    //         locality: "",
    //         parentId: 75465,
    //         unserviceable: false,
    //         veg: true,
    //         select: false,
    //         favorite: false,
    //         tradeCampaignHeaders: [],
    //         chain: [],
    //         feeDetails: {
    //             fees: [
    //                 {
    //                     name: "distance",
    //                     fee: 2300,
    //                     message: "",
    //                 },
    //                 {
    //                     name: "time",
    //                     fee: 0,
    //                     message: "",
    //                 },
    //                 {
    //                     name: "special",
    //                     fee: 0,
    //                     message: "",
    //                 },
    //             ],
    //             totalFees: 2300,
    //             message: "",
    //             title: "Delivery Charge",
    //             amount: "2300",
    //             icon: "",
    //         },
    //         availability: {
    //             opened: true,
    //             nextOpenMessage: "",
    //             nextCloseMessage: "",
    //         },
    //         longDistanceEnabled: 0,
    //         rainMode: "NONE",
    //         thirdPartyAddress: false,
    //         thirdPartyVendor: "",
    //         adTrackingID: "",
    //         badges: {
    //             imageBased: [],
    //             textBased: [],
    //             textExtendedBadges: [],
    //         },
    //         lastMileTravelString: "1.3 kms",
    //         hasSurge: false,
    //         aggregatedDiscountInfoV3: {
    //             header: "20% OFF",
    //             subHeader: "UPTO ₹50",
    //             discountTag: "",
    //             headerTypeV2: 0,
    //         },
    //         sla: {
    //             restaurantId: "63849",
    //             deliveryTime: 18,
    //             minDeliveryTime: 18,
    //             maxDeliveryTime: 18,
    //             lastMileTravel: 1.399999976158142,
    //             lastMileDistance: 0,
    //             serviceability: "SERVICEABLE",
    //             rainMode: "NONE",
    //             longDistance: "NOT_LONG_DISTANCE",
    //             preferentialService: false,
    //             iconType: "EMPTY",
    //         },
    //         promoted: false,
    //         avgRating: "3.9",
    //         totalRatings: 5000,
    //         new: false,
    //     },
    //     subtype: "basic",
    // },
    // {
    //     type: "restaurant",
    //     data: {
    //         type: "F",
    //         id: "99981",
    //         name: "Vegetariya",
    //         uuid: "475ba616-9ffa-4497-a28b-efd4a355ddf2",
    //         city: "15",
    //         area: "Hazratganj",
    //         totalRatingsString: "50+ ratings",
    //         cloudinaryImageId: "wpqtatt84b2ba56npbvk",
    //         cuisines: ["North Indian", "Chinese"],
    //         tags: [],
    //         costForTwo: 20000,
    //         costForTwoString: "₹200 FOR TWO",
    //         deliveryTime: 22,
    //         minDeliveryTime: 22,
    //         maxDeliveryTime: 22,
    //         slaString: "22 MINS",
    //         lastMileTravel: 0.6000000238418579,
    //         slugs: {
    //             restaurant: "vegetaria-hazratganj-hazratganj",
    //             city: "lucknow",
    //         },
    //         cityState: "15",
    //         address: "Saharaganj Mall Food Court, Hazratganj",
    //         locality: "Sahara Ganj Mall",
    //         parentId: 222359,
    //         unserviceable: false,
    //         veg: true,
    //         select: false,
    //         favorite: false,
    //         tradeCampaignHeaders: [],
    //         chain: [],
    //         feeDetails: {
    //             fees: [
    //                 {
    //                     name: "distance",
    //                     fee: 2300,
    //                     message: "",
    //                 },
    //                 {
    //                     name: "time",
    //                     fee: 0,
    //                     message: "",
    //                 },
    //                 {
    //                     name: "special",
    //                     fee: 0,
    //                     message: "",
    //                 },
    //             ],
    //             totalFees: 2300,
    //             message: "",
    //             title: "Delivery Charge",
    //             amount: "2300",
    //             icon: "",
    //         },
    //         availability: {
    //             opened: true,
    //             nextOpenMessage: "",
    //             nextCloseMessage: "",
    //         },
    //         longDistanceEnabled: 0,
    //         rainMode: "NONE",
    //         thirdPartyAddress: false,
    //         thirdPartyVendor: "",
    //         adTrackingID: "",
    //         badges: {
    //             imageBased: [],
    //             textBased: [],
    //             textExtendedBadges: [],
    //         },
    //         lastMileTravelString: "0.6 kms",
    //         hasSurge: false,
    //         aggregatedDiscountInfoV3: {
    //             header: "₹100 OFF",
    //             subHeader: "ABOVE ₹999",
    //             discountTag: "FLAT DEAL",
    //             headerTypeV2: 0,
    //         },
    //         sla: {
    //             restaurantId: "99981",
    //             deliveryTime: 22,
    //             minDeliveryTime: 22,
    //             maxDeliveryTime: 22,
    //             lastMileTravel: 0.6000000238418579,
    //             lastMileDistance: 0,
    //             serviceability: "SERVICEABLE",
    //             rainMode: "NONE",
    //             longDistance: "NOT_LONG_DISTANCE",
    //             preferentialService: false,
    //             iconType: "EMPTY",
    //         },
    //         promoted: false,
    //         avgRating: "2.7",
    //         totalRatings: 50,
    //         new: false,
    //     },
    //     subtype: "basic",
    // },
    // {
    //     type: "restaurant",
    //     data: {
    //         type: "F",
    //         id: "359789",
    //         name: "Grameen Kulfi",
    //         uuid: "1078f521-bfb7-4c2a-9ad5-de4d7863be9e",
    //         city: "15",
    //         area: "Hazratganj",
    //         totalRatingsString: "1000+ ratings",
    //         cloudinaryImageId: "gotbdldjbmxp8h6fxvsf",
    //         cuisines: ["Ice Cream", "Desserts"],
    //         tags: [],
    //         costForTwo: 12000,
    //         costForTwoString: "₹120 FOR TWO",
    //         deliveryTime: 13,
    //         minDeliveryTime: 13,
    //         maxDeliveryTime: 13,
    //         slaString: "13 MINS",
    //         lastMileTravel: 0.8999999761581421,
    //         slugs: {
    //             restaurant: "grameen-kulfi-hazratganj-hazratganj",
    //             city: "lucknow",
    //         },
    //         cityState: "15",
    //         address:
    //             "43/124, B M Plaza, UGF Part 3 & 4Naval Kishor Road,Hazratganj,Lucknow, UP 226001",
    //         locality: "Naval Kishor Road",
    //         parentId: 12175,
    //         unserviceable: false,
    //         veg: true,
    //         select: false,
    //         favorite: false,
    //         tradeCampaignHeaders: [],
    //         chain: [],
    //         feeDetails: {
    //             fees: [
    //                 {
    //                     name: "distance",
    //                     fee: 2300,
    //                     message: "",
    //                 },
    //                 {
    //                     name: "time",
    //                     fee: 0,
    //                     message: "",
    //                 },
    //                 {
    //                     name: "special",
    //                     fee: 0,
    //                     message: "",
    //                 },
    //             ],
    //             totalFees: 2300,
    //             message: "",
    //             title: "Delivery Charge",
    //             amount: "2300",
    //             icon: "",
    //         },
    //         availability: {
    //             opened: true,
    //             nextOpenMessage: "",
    //             nextCloseMessage: "",
    //         },
    //         longDistanceEnabled: 0,
    //         rainMode: "NONE",
    //         thirdPartyAddress: false,
    //         thirdPartyVendor: "",
    //         adTrackingID: "",
    //         badges: {
    //             imageBased: [],
    //             textBased: [],
    //             textExtendedBadges: [],
    //         },
    //         lastMileTravelString: "0.8 kms",
    //         hasSurge: false,
    //         sla: {
    //             restaurantId: "359789",
    //             deliveryTime: 13,
    //             minDeliveryTime: 13,
    //             maxDeliveryTime: 13,
    //             lastMileTravel: 0.8999999761581421,
    //             lastMileDistance: 0,
    //             serviceability: "SERVICEABLE",
    //             rainMode: "NONE",
    //             longDistance: "NOT_LONG_DISTANCE",
    //             preferentialService: false,
    //             iconType: "EMPTY",
    //         },
    //         promoted: false,
    //         avgRating: "4.6",
    //         totalRatings: 1000,
    //         new: false,
    //     },
    //     subtype: "basic",
    // },
    // {
    //     type: "restaurant",
    //     data: {
    //         type: "F",
    //         id: "581967",
    //         name: "ANNA'S DOSA",
    //         uuid: "7c4919e8-5f1b-4e72-bdc3-99bdead250fa",
    //         city: "15",
    //         area: "Hazratganj",
    //         totalRatingsString: "Too Few Ratings",
    //         cloudinaryImageId: "xfppqjjspzlm98m1x5hc",
    //         cuisines: ["South Indian", "Desserts", "Beverages"],
    //         tags: [],
    //         costForTwo: 20000,
    //         costForTwoString: "₹200 FOR TWO",
    //         deliveryTime: 21,
    //         minDeliveryTime: 21,
    //         maxDeliveryTime: 21,
    //         slaString: "21 MINS",
    //         lastMileTravel: 0.6000000238418579,
    //         slugs: {
    //             restaurant: "anna-dosa-hazratganj-hazratganj",
    //             city: "lucknow",
    //         },
    //         cityState: "15",
    //         address:
    //             "Shop No.406, 4th Floor, Saharaganj Mall, Shahnajaf Rd, Prem Nagar, Hazratganj, Lucknow, Uttar Pradesh 226001, India",
    //         locality: "Sahara Ganj Mall",
    //         parentId: 13543,
    //         unserviceable: false,
    //         veg: true,
    //         select: false,
    //         favorite: false,
    //         tradeCampaignHeaders: [],
    //         chain: [],
    //         feeDetails: {
    //             fees: [
    //                 {
    //                     name: "distance",
    //                     fee: 2300,
    //                     message: "",
    //                 },
    //                 {
    //                     name: "time",
    //                     fee: 0,
    //                     message: "",
    //                 },
    //                 {
    //                     name: "special",
    //                     fee: 0,
    //                     message: "",
    //                 },
    //             ],
    //             totalFees: 2300,
    //             message: "",
    //             title: "Delivery Charge",
    //             amount: "2300",
    //             icon: "",
    //         },
    //         availability: {
    //             opened: true,
    //             nextOpenMessage: "",
    //             nextCloseMessage: "",
    //         },
    //         longDistanceEnabled: 0,
    //         rainMode: "NONE",
    //         thirdPartyAddress: false,
    //         thirdPartyVendor: "",
    //         adTrackingID: "",
    //         badges: {
    //             imageBased: [],
    //             textBased: [],
    //             textExtendedBadges: [],
    //         },
    //         lastMileTravelString: "0.6 kms",
    //         hasSurge: false,
    //         sla: {
    //             restaurantId: "581967",
    //             deliveryTime: 21,
    //             minDeliveryTime: 21,
    //             maxDeliveryTime: 21,
    //             lastMileTravel: 0.6000000238418579,
    //             lastMileDistance: 0,
    //             serviceability: "SERVICEABLE",
    //             rainMode: "NONE",
    //             longDistance: "NOT_LONG_DISTANCE",
    //             preferentialService: false,
    //             iconType: "EMPTY",
    //         },
    //         promoted: false,
    //         avgRating: "--",
    //         totalRatings: 0,
    //         new: false,
    //     },
    //     subtype: "basic",
    // },
    // {
    //     type: "restaurant",
    //     data: {
    //         type: "F",
    //         id: "436592",
    //         name: "The Brooklyn Creamery - Healthy Ice Cream",
    //         uuid: "cc6c971c-2ab5-4a83-96a7-0a9b5f6e1287",
    //         city: "15",
    //         area: "Hazratganj",
    //         totalRatingsString: "50+ ratings",
    //         cloudinaryImageId: "b1b35780a9b1dfeb26d680506d494eaa",
    //         cuisines: ["Desserts", "Ice Cream", "Healthy Food"],
    //         tags: [],
    //         costForTwo: 20000,
    //         costForTwoString: "₹200 FOR TWO",
    //         deliveryTime: 18,
    //         minDeliveryTime: 18,
    //         maxDeliveryTime: 18,
    //         slaString: "18 MINS",
    //         lastMileTravel: 0.699999988079071,
    //         slugs: {
    //             restaurant:
    //                 "the-brooklyn-creamery-healthy-ice-cream-hazratganj-hazratganj",
    //             city: "lucknow",
    //         },
    //         cityState: "15",
    //         address:
    //             "Plot number-3A, FF, Near Indian Bank, Hazratganj, Lucknow, U.P-226023, Lucknow Tahsil, Lucknow,Uttar Pradesh, 226023",
    //         locality: "Rajeshwar Singh Marg",
    //         parentId: 236673,
    //         unserviceable: false,
    //         veg: true,
    //         select: false,
    //         favorite: false,
    //         tradeCampaignHeaders: [],
    //         chain: [],
    //         feeDetails: {
    //             fees: [
    //                 {
    //                     name: "distance",
    //                     fee: 2300,
    //                     message: "",
    //                 },
    //                 {
    //                     name: "time",
    //                     fee: 0,
    //                     message: "",
    //                 },
    //                 {
    //                     name: "special",
    //                     fee: 0,
    //                     message: "",
    //                 },
    //             ],
    //             totalFees: 2300,
    //             message: "",
    //             title: "Delivery Charge",
    //             amount: "2300",
    //             icon: "",
    //         },
    //         availability: {
    //             opened: true,
    //             nextOpenMessage: "",
    //             nextCloseMessage: "",
    //         },
    //         longDistanceEnabled: 0,
    //         rainMode: "NONE",
    //         thirdPartyAddress: false,
    //         thirdPartyVendor: "",
    //         adTrackingID: "",
    //         badges: {
    //             imageBased: [],
    //             textBased: [],
    //             textExtendedBadges: [],
    //         },
    //         lastMileTravelString: "0.6 kms",
    //         hasSurge: false,
    //         aggregatedDiscountInfoV3: {
    //             header: "50% OFF",
    //             subHeader: "UPTO ₹100",
    //             discountTag: "",
    //             headerTypeV2: 0,
    //         },
    //         sla: {
    //             restaurantId: "436592",
    //             deliveryTime: 18,
    //             minDeliveryTime: 18,
    //             maxDeliveryTime: 18,
    //             lastMileTravel: 0.699999988079071,
    //             lastMileDistance: 0,
    //             serviceability: "SERVICEABLE",
    //             rainMode: "NONE",
    //             longDistance: "NOT_LONG_DISTANCE",
    //             preferentialService: false,
    //             iconType: "EMPTY",
    //         },
    //         promoted: false,
    //         avgRating: "4.1",
    //         totalRatings: 50,
    //         new: false,
    //     },
    //     subtype: "basic",
    // },
    // {
    //     type: "restaurant",
    //     data: {
    //         type: "F",
    //         id: "73285",
    //         name: "Curry Leaf",
    //         uuid: "ea5d9b6f-144b-44c6-a29b-707eae77fde6",
    //         city: "15",
    //         area: "Hazratganj",
    //         totalRatingsString: "5000+ ratings",
    //         cloudinaryImageId: "yvgkuftflvgxfotwy3gd",
    //         cuisines: ["South Indian"],
    //         tags: [],
    //         costForTwo: 30000,
    //         costForTwoString: "₹300 FOR TWO",
    //         deliveryTime: 20,
    //         minDeliveryTime: 20,
    //         maxDeliveryTime: 20,
    //         slaString: "20 MINS",
    //         lastMileTravel: 1.399999976158142,
    //         slugs: {
    //             restaurant: "curry-leaf-hazratganj-hazratganj",
    //             city: "lucknow",
    //         },
    //         cityState: "15",
    //         address: "SHOP NO. 3, Behind HANUMAN MANDIR, HAZRATGANJ",
    //         locality: "Ashok Marg",
    //         parentId: 66911,
    //         unserviceable: false,
    //         veg: true,
    //         select: false,
    //         favorite: false,
    //         tradeCampaignHeaders: [],
    //         chain: [],
    //         feeDetails: {
    //             fees: [
    //                 {
    //                     name: "distance",
    //                     fee: 2300,
    //                     message: "",
    //                 },
    //                 {
    //                     name: "time",
    //                     fee: 0,
    //                     message: "",
    //                 },
    //                 {
    //                     name: "special",
    //                     fee: 0,
    //                     message: "",
    //                 },
    //             ],
    //             totalFees: 2300,
    //             message: "",
    //             title: "Delivery Charge",
    //             amount: "2300",
    //             icon: "",
    //         },
    //         availability: {
    //             opened: true,
    //             nextOpenMessage: "",
    //             nextCloseMessage: "",
    //         },
    //         longDistanceEnabled: 0,
    //         rainMode: "NONE",
    //         thirdPartyAddress: false,
    //         thirdPartyVendor: "",
    //         adTrackingID: "",
    //         badges: {
    //             imageBased: [],
    //             textBased: [],
    //             textExtendedBadges: [],
    //         },
    //         lastMileTravelString: "1.3 kms",
    //         hasSurge: false,
    //         aggregatedDiscountInfoV3: {
    //             header: "50% OFF",
    //             subHeader: "UPTO ₹100",
    //             discountTag: "",
    //             headerTypeV2: 0,
    //         },
    //         sla: {
    //             restaurantId: "73285",
    //             deliveryTime: 20,
    //             minDeliveryTime: 20,
    //             maxDeliveryTime: 20,
    //             lastMileTravel: 1.399999976158142,
    //             lastMileDistance: 0,
    //             serviceability: "SERVICEABLE",
    //             rainMode: "NONE",
    //             longDistance: "NOT_LONG_DISTANCE",
    //             preferentialService: false,
    //             iconType: "EMPTY",
    //         },
    //         promoted: false,
    //         avgRating: "4.2",
    //         totalRatings: 5000,
    //         new: false,
    //     },
    //     subtype: "basic",
    // },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "263838",
            name: "Pure Veg Meals by Lunchbox",
            uuid: "7b798142-8c12-453b-a994-e7cd15a41ee8",
            city: "15",
            area: "Hazratganj",
            totalRatingsString: "100+ ratings",
            cloudinaryImageId: "xxztpovi7usl8hmg5d3w",
            cuisines: ["Biryani", "North Indian", "Desserts", "Beverages"],
            tags: [],
            costForTwo: 20000,
            costForTwoString: "₹200 FOR TWO",
            deliveryTime: 22,
            minDeliveryTime: 22,
            maxDeliveryTime: 22,
            slaString: "22 MINS",
            lastMileTravel: 0.8999999761581421,
            slugs: {
                restaurant: "navratri-meals-by-faasos-hazratganj-hazratganj",
                city: "lucknow",
            },
            cityState: "15",
            address:
                "Plot number 3A, FF, Near Indian Bank, Hazratganj, Lucknow, UP 226023",
            locality: "Habibulla Estate Road",
            parentId: 21938,
            unserviceable: false,
            veg: true,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 2300,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 2300,
                message: "",
                title: "Delivery Charge",
                amount: "2300",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "0.8 kms",
            hasSurge: false,
            sla: {
                restaurantId: "263838",
                deliveryTime: 22,
                minDeliveryTime: 22,
                maxDeliveryTime: 22,
                lastMileTravel: 0.8999999761581421,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.1",
            totalRatings: 100,
            new: false,
        },
        subtype: "basic",
    },
];

